version: "5"
services:
  rabbitmq:
    image: "rabbitmq:3.12-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  postgresdb:
    image: "postgres:latest"
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql

  redisdb:
    image: "redis:latest"
    ports:
      - "6379:6379"
